### ISSUE TITLE
无意间看到你这个库，解决了我的不同设备默认摄像头默认缩放的问题。但是你的库有一处代码使用错误，我给你贴上。

### ISSUE THREAD

**Issue by CodeSlaveZhang** [hengzh0808/AVFundationCamera#1]
拍照时的setting尽量不要使用
`        
AVCapturePhotoSettings *setting = [AVCapturePhotoSettings photoSettingsWithFormat:@{AVVideoCodecKey : AVVideoCodecJPEG}];
`

因为这个setting太简略了，拍照的时候系统会自动做很多诸如白平衡、曝光补偿的事情，这将导致拍照结果与拍照前一瞬间的预览流有极大的差别。
正确应该使用如下的setting

`        
        NSArray *bracketedStillImageSettings = @[ [AVCaptureAutoExposureBracketedStillImageSettings autoExposureSettingsWithExposureTargetBias:0.]];//设置曝光补偿为0

        OSType rawFormat = [[_photoOutput.availableRawPhotoPixelFormatTypes firstObject] intValue];

        AVCapturePhotoBracketSettings *setting = [AVCapturePhotoBracketSettings photoBracketSettingsWithRawPixelFormatType:rawFormat processedFormat:nil bracketedSettings:bracketedStillImageSettings];

        setting.lensStabilizationEnabled = _photoOutput.isLensStabilizationDuringBracketedCaptureSupported;

        [_photoOutput capturePhotoWithSettings:setting delegate:self];
`

**Comment by hengzh0808** [comment]
很荣幸能帮到你，这个项目是公司的一个demo，也是主要调试多镜头了，其他的参数没有过多的干涉，你的建议我在实际项目中会进行采纳

多镜头的默认系数，我这里是添加了逻辑焦距和物理焦距的一个转换，demo代码写的不太好，实际项目中代码如下
    
    internal func caculateLogicZoomFactor(physicsZoomFactor factor: Float) -> Float {
        if containUltraWide {
            return factor / BackPhysicsLogicConvertFactor;
        }
        return factor
    }`
